//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eWorkShopAPI.Entity
{
  using System;
  using System.Data.Entity;
  using System.Data.Entity.Infrastructure;
  using System.Data.Entity.Core.Objects;
  using System.Linq;

  public partial class eWorkShop123Entities : DbContext
  {
    public eWorkShop123Entities()
        : base("name=eWorkShop123Entities")
    {
      this.Configuration.ProxyCreationEnabled = false;
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
      throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<Customer> Customers { get; set; }
    public virtual DbSet<CustomerGroup> CustomerGroups { get; set; }
    public virtual DbSet<Product> Products { get; set; }
    public virtual DbSet<ProductTicket> ProductTickets { get; set; }
    public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    public virtual DbSet<TemplateType> TemplateTypes { get; set; }
    public virtual DbSet<Ticket> Tickets { get; set; }
    public virtual DbSet<TicketTemplate> TicketTemplates { get; set; }
    public virtual DbSet<User> Users { get; set; }
    public virtual DbSet<UserType> UserTypes { get; set; }
    public virtual DbSet<Warning> Warnings { get; set; }
    public virtual DbSet<TicketInvoice> TicketInvoices { get; set; }

    public virtual ObjectResult<sp_TotalOrdersByDay_Result> sp_TotalOrdersByDay()
    {
      return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TotalOrdersByDay_Result>("sp_TotalOrdersByDay");
    }

    public virtual ObjectResult<sp_TotalOrdersByMonth_Result> sp_TotalOrdersByMonth()
    {
      return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TotalOrdersByMonth_Result>("sp_TotalOrdersByMonth");
    }

    public virtual ObjectResult<sp_TotalProductsByDay_Result> sp_TotalProductsByDay()
    {
      return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TotalProductsByDay_Result>("sp_TotalProductsByDay");
    }

    public virtual ObjectResult<sp_TotalProductsByMonth_Result> sp_TotalProductsByMonth()
    {
      return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TotalProductsByMonth_Result>("sp_TotalProductsByMonth");
    }

    public virtual ObjectResult<sp_TotalSalesByDay_Result> sp_TotalSalesByDay()
    {
      return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TotalSalesByDay_Result>("sp_TotalSalesByDay");
    }

    public virtual ObjectResult<sp_TotalSalesByMonth_Result> sp_TotalSalesByMonth()
    {
      return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TotalSalesByMonth_Result>("sp_TotalSalesByMonth");
    }
  }
}
