//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eWorkShopAPI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TemplateType()
        {
            this.TicketTemplates = new HashSet<TicketTemplate>();
        }
    
        public long TemplateTypeID { get; set; }
        public string Front { get; set; }
        public string Other { get; set; }
        public string Rear { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketTemplate> TicketTemplates { get; set; }
    }
}
