//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eWorkShopAPI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public long UserID { get; set; }
        public string Username { get; set; }
        public long Phonenumber { get; set; }
        public long Password { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedBy { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public string Email { get; set; }
        public Nullable<int> UserTypeId { get; set; }
    
        public virtual UserType UserType { get; set; }
    }
}
